"""
Mock Database cho AI Crisis Copilot.
Mỗi booking tương ứng với 1 trong 4 Paths cần demo.
"""

MOCK_BOOKINGS = {
    # ===== HAPPY PATH =====
    # Lỗi hệ thống rõ ràng → AI tự tin hoàn tiền
    "BK-78901": {
        "booking_code": "BK-78901",
        "flight": "VN123",
        "route": "HAN → SGN (Hà Nội → Hồ Chí Minh)",
        "departure": "15:30 Hôm nay",
        "passenger": "Nguyễn Văn An",
        "amount": 2500000,
        "status": "CANCELLED",
        "error_code": "GATEWAY_TIMEOUT_PARTNER",
        "error_source": "system",
        "error_detail": "Cổng thanh toán đối tác (VNPay) bị timeout lúc 09:15. Hệ thống tự động hủy vé nhưng lệnh trừ tiền đã được gửi thành công. Tiền 2,500,000đ đã bị trừ khỏi tài khoản khách.",
        "refund_eligible": True,
        "urgency_auto": "P1",
        "time_to_departure_hours": 6,
    },

    # ===== LOW-CONFIDENCE PATH =====
    # Không rõ nguyên nhân → AI cần hỏi thêm hoặc đề xuất lựa chọn
    "BK-45678": {
        "booking_code": "BK-45678",
        "flight": "VN123",
        "route": "HAN → SGN (Hà Nội → Hồ Chí Minh)",
        "departure": "15:30 Hôm nay",
        "passenger": "Trần Thị Bình",
        "amount": 2500000,
        "status": "CANCELLED",
        "error_code": "UNKNOWN_REASON",
        "error_source": "unknown",
        "error_detail": "Không xác định được nguyên nhân hủy vé. Log giao dịch ghi nhận trạng thái 'cancelled' nhưng không có mã lỗi từ cổng thanh toán lẫn hãng bay.",
        "refund_eligible": None,
        "urgency_auto": "P2",
        "time_to_departure_hours": 6,
    },

    # ===== FAILURE PATH =====
    # Không có log giao dịch → AI bất lực, phải chuyển người thật
    "BK-99999": {
        "booking_code": "BK-99999",
        "flight": "VN123",
        "route": "HAN → SGN (Hà Nội → Hồ Chí Minh)",
        "departure": "15:30 Hôm nay",
        "passenger": "Lê Văn Cường",
        "amount": 2500000,
        "status": "CANCELLED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": None,
        "urgency_auto": None,
        "time_to_departure_hours": 6,
    },

    # ===== CORRECTION PATH =====
    # Dữ liệu hệ thống SAI ngày bay → AI đánh giá sai mức ưu tiên
    # Thực tế chuyến bay là HÔM NAY nhưng hệ thống ghi sai là 15/10/2026
    "BK-11111": {
        "booking_code": "BK-11111",
        "flight": "VN123",
        "route": "HAN → SGN (Hà Nội → Hồ Chí Minh)",
        "departure": "15:30 ngày 15/10/2026",
        "passenger": "Phạm Văn Dũng",
        "amount": 2500000,
        "status": "CANCELLED",
        "error_code": "AIRLINE_SCHEDULE_CHANGE",
        "error_source": "airline",
        "error_detail": "Hãng hàng không thay đổi lịch bay. Vé bị hủy tự động theo chính sách của hãng.",
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 2160,
        "note": "Ưu tiên thấp (P3). Xử lý hoàn tiền theo chính sách hãng bay trong 7-14 ngày làm việc.",
    },

    # ===== EXTRA CLEAN SAMPLE DATA =====
    # Booking bình thường, dữ liệu đầy đủ, không lỗi
    "BK-22222": {
        "booking_code": "BK-22222",
        "flight": "VN245",
        "route": "DAD → SGN (Đà Nẵng → Hồ Chí Minh)",
        "departure": "19:20 Hôm nay",
        "passenger": "Ngô Thị Hà",
        "amount": 1890000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 8,
        "note": "Đặt vé thành công, không ghi nhận bất thường.",
    },
    "BK-33333": {
        "booking_code": "BK-33333",
        "flight": "QH1815",
        "route": "HAN → DLI (Hà Nội → Đà Lạt)",
        "departure": "06:10 Ngày mai",
        "passenger": "Vũ Minh Khang",
        "amount": 2150000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 15,
        "note": "Booking ổn định, có thể đổi chuyến theo chính sách linh hoạt.",
    },
    "BK-44444": {
        "booking_code": "BK-44444",
        "flight": "VN128",
        "route": "SGN → HAN (Hồ Chí Minh → Hà Nội)",
        "departure": "21:45 Hôm nay",
        "passenger": "Đặng Quốc Bảo",
        "amount": 2390000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 10,
        "note": "Đơn hợp lệ, hỗ trợ đổi chuyến cùng ngày nếu còn chỗ.",
    },
    "BK-55555": {
        "booking_code": "BK-55555",
        "flight": "VJ302",
        "route": "HAN → DAD (Hà Nội → Đà Nẵng)",
        "departure": "11:40 Hôm nay",
        "passenger": "Phan Đức Nam",
        "amount": 1450000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 2,
        "note": "Booking chuẩn, có các lựa chọn đổi chuyến phụ thu.",
    },
    "BK-66666": {
        "booking_code": "BK-66666",
        "flight": "VN650",
        "route": "HUI → SGN (Huế → Hồ Chí Minh)",
        "departure": "17:15 Hôm nay",
        "passenger": "Mai Thu Trang",
        "amount": 1710000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 7,
        "note": "Booking chuẩn, đổi chuyến có thể nhận voucher hoàn tiền.",
    },
    "BK-77777": {
        "booking_code": "BK-77777",
        "flight": "QH225",
        "route": "SGN → CXR (Hồ Chí Minh → Nha Trang)",
        "departure": "14:25 Hôm nay",
        "passenger": "Trịnh Gia Hưng",
        "amount": 1320000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 4,
        "note": "Booking chuẩn, đổi chuyến có thể phát sinh phí dịch vụ.",
    },
    "BK-88888": {
        "booking_code": "BK-88888",
        "flight": "VN781",
        "route": "SGN → PQC (Hồ Chí Minh → Phú Quốc)",
        "departure": "08:55 Ngày mai",
        "passenger": "Đỗ Hồng Ngọc",
        "amount": 1980000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 18,
        "note": "Booking chuẩn, có nhiều phương án đổi chuyến hỗn hợp.",
    },
    "BK-99998": {
        "booking_code": "BK-99998",
        "flight": "VJ915",
        "route": "HAN → BMV (Hà Nội → Buôn Ma Thuột)",
        "departure": "06:20 Ngày mai",
        "passenger": "Nguyễn Khánh Linh",
        "amount": 1640000,
        "status": "CONFIRMED",
        "error_code": None,
        "error_source": None,
        "error_detail": None,
        "refund_eligible": False,
        "urgency_auto": "P3",
        "time_to_departure_hours": 16,
        "note": "Booking chuẩn, có case phụ thu thấp và case hoàn tiền.",
    },
}

ALTERNATIVE_FLIGHTS = {
    "BK-78901": [
        {
            "flight_id": "ALT-78901-1",
            "flight": "VN125",
            "route": "HAN → SGN",
            "departure": "18:45 Hôm nay",
            "arrival": "20:50 Hôm nay",
            "seat_available": "14C (Economy)",
            "price_difference": 0,
            "note": "Chuyến tương đương, không phụ thu.",
        },
        {
            "flight_id": "ALT-78901-2",
            "flight": "VJ167",
            "route": "HAN → SGN",
            "departure": "20:10 Hôm nay",
            "arrival": "22:20 Hôm nay",
            "seat_available": "18A (Economy)",
            "price_difference": -120000,
            "note": "Rẻ hơn chuyến cũ 120,000đ.",
        },
    ],
    "BK-45678": [
        {
            "flight_id": "ALT-45678-1",
            "flight": "VN135",
            "route": "HAN → SGN",
            "departure": "17:30 Hôm nay",
            "arrival": "19:35 Hôm nay",
            "seat_available": "10D (Economy)",
            "price_difference": 0,
            "note": "Ưu tiên gần giờ bay, giữ hạng vé tương đương.",
        },
        {
            "flight_id": "ALT-45678-2",
            "flight": "QH210",
            "route": "HAN → SGN",
            "departure": "19:05 Hôm nay",
            "arrival": "21:15 Hôm nay",
            "seat_available": "22F (Economy)",
            "price_difference": 90000,
            "note": "Phụ thu 90,000đ do thay đổi hãng bay.",
        },
        {
            "flight_id": "ALT-45678-3",
            "flight": "VN151",
            "route": "HAN → SGN",
            "departure": "21:40 Hôm nay",
            "arrival": "23:45 Hôm nay",
            "seat_available": "09A (Economy Flex)",
            "price_difference": 150000,
            "note": "Hạng linh hoạt, hỗ trợ hoàn/đổi dễ hơn.",
        },
    ],
    "BK-22222": [
        {
            "flight_id": "ALT-22222-1",
            "flight": "VJ641",
            "route": "DAD → SGN",
            "departure": "21:00 Hôm nay",
            "arrival": "22:25 Hôm nay",
            "seat_available": "16B (Economy)",
            "price_difference": 0,
            "note": "Không phụ thu.",
        },
        {
            "flight_id": "ALT-22222-2",
            "flight": "VN253",
            "route": "DAD → SGN",
            "departure": "22:10 Hôm nay",
            "arrival": "23:35 Hôm nay",
            "seat_available": "11A (Economy)",
            "price_difference": 70000,
            "note": "Phụ thu 70,000đ.",
        },
    ],
    # ===== SURCHARGE CASES =====
    "BK-55555": [
        {
            "flight_id": "ALT-55555-1",
            "flight": "VN170",
            "route": "HAN → DAD",
            "departure": "13:20 Hôm nay",
            "arrival": "14:45 Hôm nay",
            "seat_available": "12A (Economy)",
            "price_difference": 180000,
            "note": "Phụ thu do khung giờ cao điểm.",
        },
        {
            "flight_id": "ALT-55555-2",
            "flight": "QH108",
            "route": "HAN → DAD",
            "departure": "15:05 Hôm nay",
            "arrival": "16:30 Hôm nay",
            "seat_available": "08D (Economy)",
            "price_difference": 260000,
            "note": "Phụ thu do hãng bay khác và ít ghế trống.",
        },
    ],
    # ===== REFUND CASES =====
    "BK-66666": [
        {
            "flight_id": "ALT-66666-1",
            "flight": "VJ805",
            "route": "HUI → SGN",
            "departure": "19:05 Hôm nay",
            "arrival": "20:35 Hôm nay",
            "seat_available": "17C (Economy)",
            "price_difference": -90000,
            "note": "Giá vé thấp hơn, hoàn voucher 90,000đ.",
        },
        {
            "flight_id": "ALT-66666-2",
            "flight": "QH051",
            "route": "HUI → SGN",
            "departure": "20:40 Hôm nay",
            "arrival": "22:10 Hôm nay",
            "seat_available": "14A (Economy)",
            "price_difference": -150000,
            "note": "Giá vé thấp hơn, hoàn voucher 150,000đ.",
        },
    ],
    # ===== EXTRA FEE CASES =====
    "BK-77777": [
        {
            "flight_id": "ALT-77777-1",
            "flight": "VN233",
            "route": "SGN → CXR",
            "departure": "16:55 Hôm nay",
            "arrival": "18:00 Hôm nay",
            "seat_available": "21F (Economy)",
            "price_difference": 120000,
            "handling_fee": 30000,
            "note": "Thu thêm phí xử lý đổi vé 30,000đ (gộp vào phụ thu).",
        },
        {
            "flight_id": "ALT-77777-2",
            "flight": "VJ617",
            "route": "SGN → CXR",
            "departure": "18:30 Hôm nay",
            "arrival": "19:35 Hôm nay",
            "seat_available": "10C (Economy)",
            "price_difference": 70000,
            "handling_fee": 20000,
            "note": "Thu thêm phí dịch vụ đổi vé 20,000đ (gộp vào phụ thu).",
        },
    ],
    "BK-88888": [
        {
            "flight_id": "ALT-88888-1",
            "flight": "VJ332",
            "route": "SGN → PQC",
            "departure": "10:20 Ngày mai",
            "arrival": "11:20 Ngày mai",
            "seat_available": "15A (Economy)",
            "price_difference": 0,
            "note": "Đổi ngang giá, không phát sinh phí.",
        },
        {
            "flight_id": "ALT-88888-2",
            "flight": "VN745",
            "route": "SGN → PQC",
            "departure": "12:05 Ngày mai",
            "arrival": "13:05 Ngày mai",
            "seat_available": "09D (Economy Flex)",
            "price_difference": 240000,
            "handling_fee": 40000,
            "note": "Phụ thu + phí dịch vụ do đổi sang hạng linh hoạt.",
        },
        {
            "flight_id": "ALT-88888-3",
            "flight": "QH387",
            "route": "SGN → PQC",
            "departure": "14:50 Ngày mai",
            "arrival": "15:50 Ngày mai",
            "seat_available": "18B (Economy)",
            "price_difference": -110000,
            "note": "Giá thấp hơn, hoàn voucher 110,000đ.",
        },
    ],
    "BK-99998": [
        {
            "flight_id": "ALT-99998-1",
            "flight": "VN913",
            "route": "HAN → BMV",
            "departure": "07:45 Ngày mai",
            "arrival": "09:30 Ngày mai",
            "seat_available": "13A (Economy)",
            "price_difference": 50000,
            "note": "Phụ thu nhẹ do thay đổi khung giờ.",
        },
        {
            "flight_id": "ALT-99998-2",
            "flight": "QH990",
            "route": "HAN → BMV",
            "departure": "09:10 Ngày mai",
            "arrival": "10:55 Ngày mai",
            "seat_available": "22D (Economy)",
            "price_difference": -80000,
            "note": "Giá thấp hơn, hoàn voucher 80,000đ.",
        },
    ],
}

# Mapping scenario names to booking codes (for Dev Panel)
SCENARIO_BOOKING_MAP = {
    "happy": "BK-78901",
    "low_confidence": "BK-45678",
    "failure": "BK-99999",
    "correction": "BK-11111",
    "clean_case_1": "BK-22222",
    "clean_case_2": "BK-33333",
    "clean_case_3": "BK-44444",
    "clean_surcharge": "BK-55555",
    "clean_refund": "BK-66666",
    "clean_extra_fee": "BK-77777",
    "clean_mixed_1": "BK-88888",
    "clean_mixed_2": "BK-99998",
}